package commands

import (
	"database/sql"
	"os"
	"path/filepath"
	"sort"
	"testing"

	_ "modernc.org/sqlite"
)

func TestInitCreatesAllArtefacts(t *testing.T) {
	dir := t.TempDir()
	if err := runInit(dir, "demo", false); err != nil {
		t.Fatalf("runInit: %v", err)
	}
	for _, name := range []string{"config.toml", "policies.toml", "govforge.db"} {
		p := filepath.Join(dir, ".govforge", name)
		info, err := os.Stat(p)
		if err != nil {
			t.Fatalf("%s missing: %v", name, err)
		}
		if info.Size() == 0 {
			t.Fatalf("%s is empty", name)
		}
	}
}

func TestInitDatabaseHasExpectedTables(t *testing.T) {
	dir := t.TempDir()
	if err := runInit(dir, "demo", false); err != nil {
		t.Fatalf("runInit: %v", err)
	}
	db, err := sql.Open("sqlite", filepath.Join(dir, ".govforge", "govforge.db"))
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer func() { _ = db.Close() }()

	rows, err := db.Query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
	if err != nil {
		t.Fatalf("query: %v", err)
	}
	defer func() { _ = rows.Close() }()

	got := []string{}
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			t.Fatalf("scan: %v", err)
		}
		got = append(got, n)
	}
	want := []string{
		"agents", "approvals", "decisions", "disagreements", "events",
		"findings", "git_changes", "policies", "policy_results",
		"projects", "reviews", "tasks",
	}
	sort.Strings(got)
	sort.Strings(want)
	if len(got) != len(want) {
		t.Fatalf("table count mismatch: got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("table %d: got %q want %q (full got=%v)", i, got[i], want[i], got)
		}
	}
}

func TestInitRefusesToOverwriteWithoutForce(t *testing.T) {
	dir := t.TempDir()
	if err := runInit(dir, "demo", false); err != nil {
		t.Fatalf("first runInit: %v", err)
	}
	if err := runInit(dir, "demo", false); err == nil {
		t.Fatal("expected error on second init without --force")
	}
}

func TestInitWithForceOverwritesConfigOnly(t *testing.T) {
	dir := t.TempDir()
	if err := runInit(dir, "demo", false); err != nil {
		t.Fatalf("first runInit: %v", err)
	}
	cfg := filepath.Join(dir, ".govforge", "config.toml")
	if err := os.WriteFile(cfg, []byte("# overwritten"), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	if err := runInit(dir, "demo", true); err != nil {
		t.Fatalf("force runInit: %v", err)
	}
	body, err := os.ReadFile(cfg)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(body) == "# overwritten" {
		t.Fatal("expected config to be regenerated by --force")
	}
}
