"""SQLAlchemy 2 ORM models for the GovForge domain.

Conventions
-----------

- Primary key `id` is always a UUID (stored as TEXT in SQLite).
- User-facing identifiers are `display_id` strings (`TASK-001`, `DEC-042`),
  unique per `(project_id, prefix)`. Generated by services, not the DB.
- Every mutating entity has `created_at` and `updated_at`. The `Event` table
  is append-only and only has `created_at`.
- Enums are stored as VARCHAR using SQLAlchemy `Enum(...)`. Adding a new
  variant requires an Alembic migration to relax the CHECK constraint.
- JSON columns use the cross-db `JSON` type — SQLite stores as TEXT and
  parses on read.
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID, uuid4

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Uuid,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
)

from govforge.core.enums import (
    AgentType,
    ApprovalStatus,
    AuthProvider,
    DecisionStatus,
    FindingCategory,
    FindingSeverity,
    PolicyResultStatus,
    ReviewStatus,
    RiskLevel,
    TaskStatus,
    TokenScope,
)


def _now() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


class TimestampMixin:
    """Adds created_at / updated_at columns with UTC defaults."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_now,
        onupdate=_now,
        nullable=False,
    )


# ---------------------------------------------------------------------------
# Project — root aggregate
# ---------------------------------------------------------------------------


class Project(TimestampMixin, Base):
    __tablename__ = "projects"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    root_path: Mapped[str] = mapped_column(String(1024), nullable=False, unique=True)
    default_branch: Mapped[str] = mapped_column(String(255), default="main", nullable=False)

    tasks: Mapped[list[Task]] = relationship(back_populates="project", cascade="all, delete-orphan")
    decisions: Mapped[list[Decision]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )
    events: Mapped[list[Event]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )


# ---------------------------------------------------------------------------
# Agent — humans + AI agents
# ---------------------------------------------------------------------------


class Agent(Base):
    __tablename__ = "agents"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    type: Mapped[AgentType] = mapped_column(Enum(AgentType, name="agent_type"), nullable=False)
    metadata_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )


# ---------------------------------------------------------------------------
# Task
# ---------------------------------------------------------------------------


class Task(TimestampMixin, Base):
    __tablename__ = "tasks"
    __table_args__ = (
        UniqueConstraint("project_id", "display_id", name="uq_tasks_project_display"),
        Index("ix_tasks_project_status", "project_id", "status"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    display_id: Mapped[str] = mapped_column(String(32), nullable=False)
    project_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, name="risk_level"), default=RiskLevel.MEDIUM, nullable=False
    )
    status: Mapped[TaskStatus] = mapped_column(
        Enum(TaskStatus, name="task_status"), default=TaskStatus.OPEN, nullable=False
    )
    created_by_agent_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=True
    )

    project: Mapped[Project] = relationship(back_populates="tasks")
    decisions: Mapped[list[Decision]] = relationship(back_populates="task")


# ---------------------------------------------------------------------------
# Decision — central primitive
# ---------------------------------------------------------------------------


class Decision(TimestampMixin, Base):
    __tablename__ = "decisions"
    __table_args__ = (
        UniqueConstraint("project_id", "display_id", name="uq_decisions_project_display"),
        Index("ix_decisions_project_status", "project_id", "status"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    display_id: Mapped[str] = mapped_column(String(32), nullable=False)
    project_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    task_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("tasks.id", ondelete="SET NULL"), nullable=True
    )
    author_agent_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("agents.id"), nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[DecisionStatus] = mapped_column(
        Enum(DecisionStatus, name="decision_status"),
        default=DecisionStatus.DRAFT,
        nullable=False,
    )
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, name="risk_level"), default=RiskLevel.MEDIUM, nullable=False
    )
    human_approval_required: Mapped[bool] = mapped_column(default=False, nullable=False)

    project: Mapped[Project] = relationship(back_populates="decisions")
    task: Mapped[Task | None] = relationship(back_populates="decisions")
    git_changes: Mapped[list[GitChange]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    reviews: Mapped[list[Review]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    policy_results: Mapped[list[PolicyResult]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    disagreements: Mapped[list[Disagreement]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    approvals: Mapped[list[Approval]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )


# ---------------------------------------------------------------------------
# GitChange — link decision ↔ commit/diff
# ---------------------------------------------------------------------------


class GitChange(Base):
    __tablename__ = "git_changes"
    __table_args__ = (
        Index("ix_git_changes_commit", "commit_hash"),
        Index("ix_git_changes_decision", "decision_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    repo_path: Mapped[str] = mapped_column(String(1024), nullable=False)
    branch_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    commit_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    parent_commit_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    diff_hash: Mapped[str | None] = mapped_column(String(72), nullable=True)
    files_changed_json: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    insertions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    deletions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="git_changes")


# ---------------------------------------------------------------------------
# Review + Finding
# ---------------------------------------------------------------------------


class Review(Base):
    __tablename__ = "reviews"
    __table_args__ = (Index("ix_reviews_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    display_id: Mapped[str] = mapped_column(String(32), nullable=False)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    reviewer_agent_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("agents.id"), nullable=False)
    status: Mapped[ReviewStatus] = mapped_column(
        Enum(ReviewStatus, name="review_status"), nullable=False
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="reviews")
    findings: Mapped[list[Finding]] = relationship(
        back_populates="review", cascade="all, delete-orphan"
    )


class Finding(Base):
    __tablename__ = "findings"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    review_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("reviews.id", ondelete="CASCADE"), nullable=False
    )
    severity: Mapped[FindingSeverity] = mapped_column(
        Enum(FindingSeverity, name="finding_severity"), nullable=False
    )
    category: Mapped[FindingCategory] = mapped_column(
        Enum(FindingCategory, name="finding_category"), nullable=False
    )
    file_path: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    line_start: Mapped[int | None] = mapped_column(Integer, nullable=True)
    line_end: Mapped[int | None] = mapped_column(Integer, nullable=True)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    recommendation: Mapped[str | None] = mapped_column(Text, nullable=True)

    review: Mapped[Review] = relationship(back_populates="findings")


# ---------------------------------------------------------------------------
# Policy + PolicyResult
# ---------------------------------------------------------------------------


class Policy(Base):
    __tablename__ = "policies"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    enabled: Mapped[bool] = mapped_column(default=True, nullable=False)
    severity: Mapped[FindingSeverity] = mapped_column(
        Enum(FindingSeverity, name="finding_severity"),
        default=FindingSeverity.MEDIUM,
        nullable=False,
    )
    config_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )


class PolicyResult(Base):
    __tablename__ = "policy_results"
    __table_args__ = (Index("ix_policy_results_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    policy_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("policies.id"), nullable=False)
    status: Mapped[PolicyResultStatus] = mapped_column(
        Enum(PolicyResultStatus, name="policy_result_status"), nullable=False
    )
    message: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="policy_results")


# ---------------------------------------------------------------------------
# Disagreement
# ---------------------------------------------------------------------------


class Disagreement(Base):
    __tablename__ = "disagreements"
    __table_args__ = (Index("ix_disagreements_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    topic: Mapped[str] = mapped_column(String(512), nullable=False)
    author_position: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewer_position: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    requires_human_decision: Mapped[bool] = mapped_column(default=True, nullable=False)
    resolution: Mapped[str | None] = mapped_column(Text, nullable=True)
    resolved_by_agent_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="disagreements")


# ---------------------------------------------------------------------------
# Approval
# ---------------------------------------------------------------------------


class Approval(Base):
    __tablename__ = "approvals"
    __table_args__ = (Index("ix_approvals_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    approver_agent_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("agents.id"), nullable=False)
    status: Mapped[ApprovalStatus] = mapped_column(
        Enum(ApprovalStatus, name="approval_status"), nullable=False
    )
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="approvals")


# ---------------------------------------------------------------------------
# Event — append-only audit log
# ---------------------------------------------------------------------------


class Event(Base):
    __tablename__ = "events"
    __table_args__ = (
        Index("ix_events_project_created", "project_id", "created_at"),
        Index("ix_events_entity", "entity_type", "entity_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    project_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[UUID] = mapped_column(Uuid, nullable=False)
    event_type: Mapped[str] = mapped_column(String(128), nullable=False)
    actor_agent_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=True
    )
    payload_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    project: Mapped[Project] = relationship(back_populates="events")


# ---------------------------------------------------------------------------
# Auth — User + ApiToken (Phase 3.0 Stage A — pulled forward 2026-05-10)
# ---------------------------------------------------------------------------


class User(TimestampMixin, Base):
    """End-user of GovForge. Phase 3.0 Stage A: created via bootstrap script
    only (no signup UI). Stage B adds OAuth-based creation via `Account`."""

    __tablename__ = "users"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    email: Mapped[str] = mapped_column(String(320), nullable=False, unique=True)
    display_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    avatar_url: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)

    tokens: Mapped[list[ApiToken]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    accounts: Mapped[list[Account]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    sessions: Mapped[list[Session]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class Account(TimestampMixin, Base):
    """OAuth identity linked to a `User`. One row per (provider, provider_user_id).

    Stage B adds GitHub. Google + magic_link slots are reserved in
    `AuthProvider`; rows show up when those providers ship.
    """

    __tablename__ = "accounts"
    __table_args__ = (
        UniqueConstraint(
            "provider", "provider_user_id", name="uq_accounts_provider_user_id"
        ),
        Index("ix_accounts_user_id", "user_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("users.id"), nullable=False)
    provider: Mapped[AuthProvider] = mapped_column(
        Enum(AuthProvider, native_enum=False, length=32), nullable=False
    )
    # Provider's stable user ID (e.g. GitHub's numeric `id`, Google's `sub`).
    provider_user_id: Mapped[str] = mapped_column(String(255), nullable=False)
    # Provider's primary email at link time (informational, not unique).
    provider_email: Mapped[str | None] = mapped_column(String(320), nullable=True)
    # Provider's display handle (GitHub login, Google name, etc.).
    provider_login: Mapped[str | None] = mapped_column(String(255), nullable=True)

    user: Mapped[User] = relationship(back_populates="accounts")


class Session(Base):
    """Cookie-backed session for the marketing site + cockpit UI.

    The cookie sent to the browser carries `<session_id>.<signature>`
    where the signature is HMAC-SHA256(session_id, GOVFORGE_COOKIE_SECRET).
    Server-side verification rejects sessions with bad signatures BEFORE
    a DB lookup. Lookup is by `id` (UUID) once the signature validates.

    Sessions auto-expire after `GOVFORGE_SESSION_TTL_DAYS` (default 30).
    Revocation = setting `revoked_at`.
    """

    __tablename__ = "sessions"
    __table_args__ = (
        Index("ix_sessions_user_id", "user_id"),
        Index("ix_sessions_expires_at", "expires_at"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("users.id"), nullable=False)
    user_agent: Mapped[str | None] = mapped_column(String(512), nullable=True)
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    user: Mapped[User] = relationship(back_populates="sessions")

    @property
    def is_active(self) -> bool:
        if self.revoked_at is not None:
            return False
        # SQLite strips tzinfo on read; coerce to UTC for comparison.
        exp = self.expires_at
        if exp.tzinfo is None:
            exp = exp.replace(tzinfo=UTC)
        return exp > _now()


class ApiToken(Base):
    """Bearer token issued to a `User` for CLI / MCP / programmatic API access.

    Storage model: only the *hash* of the secret is stored. The plaintext
    value is shown to the user once at creation time and is unrecoverable
    after that. Lookup happens by the `prefix` (first 8 chars of the
    secret, indexed) plus a constant-time hash comparison.

    `scopes_csv` is a comma-separated list of `TokenScope` values. The
    `RequireToken(scope=...)` dependency parses it on each request and
    accepts the call iff the requested scope is in the list, OR the list
    includes `admin`.

    `agent_type` is informational: it goes into the audit log so we know
    which agent class drove a given decision. It does NOT gate access —
    the scope list does that.
    """

    __tablename__ = "api_tokens"
    __table_args__ = (
        Index("ix_api_tokens_prefix", "prefix"),
        Index("ix_api_tokens_user_id", "user_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    user_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("users.id"), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    agent_type: Mapped[AgentType] = mapped_column(
        Enum(AgentType, native_enum=False, length=32), nullable=False
    )
    # 8-char public prefix used to narrow the lookup before the constant-time hash check.
    prefix: Mapped[str] = mapped_column(String(8), nullable=False)
    # SHA-256 hex digest of the full secret (length 64).
    hashed_secret: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    # CSV of TokenScope values, e.g. "decisions:write,reviews:read".
    scopes_csv: Mapped[str] = mapped_column(Text, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    last_used_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    user: Mapped[User] = relationship(back_populates="tokens")

    @property
    def scopes(self) -> list[TokenScope]:
        return [TokenScope(s) for s in self.scopes_csv.split(",") if s]

    @scopes.setter
    def scopes(self, value: list[TokenScope]) -> None:
        self.scopes_csv = ",".join(s.value for s in value)

    def has_scope(self, scope: TokenScope) -> bool:
        scopes = self.scopes
        return TokenScope.ADMIN in scopes or scope in scopes

    @property
    def is_revoked(self) -> bool:
        return self.revoked_at is not None

    @property
    def is_expired(self) -> bool:
        return self.expires_at is not None and self.expires_at <= _now()

    @property
    def is_active(self) -> bool:
        return not self.is_revoked and not self.is_expired


class DeviceCode(Base):
    """Pending OAuth-style device authorization for `gf auth login --device`.

    The CLI requests a device code, prints the user_code + URL to the
    terminal, and polls until the user opens the URL in a browser and
    approves. Approval creates an `ApiToken` and links it here; the
    next poll returns the token's plaintext secret.

    Storage model: only `device_code_hash` (sha256 of the high-entropy
    secret the CLI holds) is stored; the user_code is stored in clear
    because it's a short low-entropy string typed by a human and only
    valid for ~10 minutes against an expiring row.
    """

    __tablename__ = "device_codes"
    __table_args__ = (
        UniqueConstraint("user_code", name="uq_device_codes_user_code"),
        Index("ix_device_codes_device_code_hash", "device_code_hash"),
        Index("ix_device_codes_expires_at", "expires_at"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    # SHA-256 hex digest of the secret the CLI polls with.
    device_code_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    # 8-char human-typable code, e.g. "ABCD-EFGH". Stored uppercase, no padding.
    user_code: Mapped[str] = mapped_column(String(16), nullable=False)
    # Free-form label + agent_type the CLI requested for the eventual token.
    requested_label: Mapped[str] = mapped_column(String(255), nullable=False)
    requested_agent_type: Mapped[AgentType] = mapped_column(
        Enum(AgentType, native_enum=False, length=32), nullable=False
    )
    # Approver: set when a logged-in user POSTs /auth/device/approve.
    user_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id"), nullable=True
    )
    # The ApiToken issued at approval time; null until approved.
    token_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("api_tokens.id"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    @property
    def is_expired(self) -> bool:
        exp = self.expires_at
        if exp.tzinfo is None:
            exp = exp.replace(tzinfo=UTC)
        return exp <= _now()

    @property
    def is_approved(self) -> bool:
        return self.approved_at is not None and self.token_id is not None


__all__ = [
    "Account",
    "Agent",
    "ApiToken",
    "Approval",
    "Base",
    "Decision",
    "DeviceCode",
    "Disagreement",
    "Event",
    "Finding",
    "GitChange",
    "Policy",
    "PolicyResult",
    "Project",
    "Review",
    "Session",
    "Task",
    "User",
]
