"""SQLAlchemy 2 ORM models for the GovForge domain.

Conventions
-----------

- Primary key `id` is always a UUID (stored as TEXT in SQLite).
- User-facing identifiers are `display_id` strings (`TASK-001`, `DEC-042`),
  unique per `(project_id, prefix)`. Generated by services, not the DB.
- Every mutating entity has `created_at` and `updated_at`. The `Event` table
  is append-only and only has `created_at`.
- Enums are stored as VARCHAR using SQLAlchemy `Enum(...)`. Adding a new
  variant requires an Alembic migration to relax the CHECK constraint.
- JSON columns use the cross-db `JSON` type — SQLite stores as TEXT and
  parses on read.
"""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID, uuid4

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Uuid,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
)

from govforge.core.enums import (
    AgentType,
    ApprovalStatus,
    DecisionStatus,
    FindingCategory,
    FindingSeverity,
    PolicyResultStatus,
    ReviewStatus,
    RiskLevel,
    TaskStatus,
)


def _now() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


class TimestampMixin:
    """Adds created_at / updated_at columns with UTC defaults."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_now,
        onupdate=_now,
        nullable=False,
    )


# ---------------------------------------------------------------------------
# Project — root aggregate
# ---------------------------------------------------------------------------


class Project(TimestampMixin, Base):
    __tablename__ = "projects"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    root_path: Mapped[str] = mapped_column(String(1024), nullable=False, unique=True)
    default_branch: Mapped[str] = mapped_column(String(255), default="main", nullable=False)

    tasks: Mapped[list[Task]] = relationship(back_populates="project", cascade="all, delete-orphan")
    decisions: Mapped[list[Decision]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )
    events: Mapped[list[Event]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )


# ---------------------------------------------------------------------------
# Agent — humans + AI agents
# ---------------------------------------------------------------------------


class Agent(Base):
    __tablename__ = "agents"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    type: Mapped[AgentType] = mapped_column(Enum(AgentType, name="agent_type"), nullable=False)
    metadata_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )


# ---------------------------------------------------------------------------
# Task
# ---------------------------------------------------------------------------


class Task(TimestampMixin, Base):
    __tablename__ = "tasks"
    __table_args__ = (
        UniqueConstraint("project_id", "display_id", name="uq_tasks_project_display"),
        Index("ix_tasks_project_status", "project_id", "status"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    display_id: Mapped[str] = mapped_column(String(32), nullable=False)
    project_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, name="risk_level"), default=RiskLevel.MEDIUM, nullable=False
    )
    status: Mapped[TaskStatus] = mapped_column(
        Enum(TaskStatus, name="task_status"), default=TaskStatus.OPEN, nullable=False
    )
    created_by_agent_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=True
    )

    project: Mapped[Project] = relationship(back_populates="tasks")
    decisions: Mapped[list[Decision]] = relationship(back_populates="task")


# ---------------------------------------------------------------------------
# Decision — central primitive
# ---------------------------------------------------------------------------


class Decision(TimestampMixin, Base):
    __tablename__ = "decisions"
    __table_args__ = (
        UniqueConstraint("project_id", "display_id", name="uq_decisions_project_display"),
        Index("ix_decisions_project_status", "project_id", "status"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    display_id: Mapped[str] = mapped_column(String(32), nullable=False)
    project_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    task_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("tasks.id", ondelete="SET NULL"), nullable=True
    )
    author_agent_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("agents.id"), nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[DecisionStatus] = mapped_column(
        Enum(DecisionStatus, name="decision_status"),
        default=DecisionStatus.DRAFT,
        nullable=False,
    )
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, name="risk_level"), default=RiskLevel.MEDIUM, nullable=False
    )
    human_approval_required: Mapped[bool] = mapped_column(default=False, nullable=False)

    project: Mapped[Project] = relationship(back_populates="decisions")
    task: Mapped[Task | None] = relationship(back_populates="decisions")
    git_changes: Mapped[list[GitChange]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    reviews: Mapped[list[Review]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    policy_results: Mapped[list[PolicyResult]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    disagreements: Mapped[list[Disagreement]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )
    approvals: Mapped[list[Approval]] = relationship(
        back_populates="decision", cascade="all, delete-orphan"
    )


# ---------------------------------------------------------------------------
# GitChange — link decision ↔ commit/diff
# ---------------------------------------------------------------------------


class GitChange(Base):
    __tablename__ = "git_changes"
    __table_args__ = (
        Index("ix_git_changes_commit", "commit_hash"),
        Index("ix_git_changes_decision", "decision_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    repo_path: Mapped[str] = mapped_column(String(1024), nullable=False)
    branch_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    commit_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    parent_commit_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    diff_hash: Mapped[str | None] = mapped_column(String(72), nullable=True)
    files_changed_json: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    insertions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    deletions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="git_changes")


# ---------------------------------------------------------------------------
# Review + Finding
# ---------------------------------------------------------------------------


class Review(Base):
    __tablename__ = "reviews"
    __table_args__ = (Index("ix_reviews_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    display_id: Mapped[str] = mapped_column(String(32), nullable=False)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    reviewer_agent_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("agents.id"), nullable=False)
    status: Mapped[ReviewStatus] = mapped_column(
        Enum(ReviewStatus, name="review_status"), nullable=False
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="reviews")
    findings: Mapped[list[Finding]] = relationship(
        back_populates="review", cascade="all, delete-orphan"
    )


class Finding(Base):
    __tablename__ = "findings"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    review_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("reviews.id", ondelete="CASCADE"), nullable=False
    )
    severity: Mapped[FindingSeverity] = mapped_column(
        Enum(FindingSeverity, name="finding_severity"), nullable=False
    )
    category: Mapped[FindingCategory] = mapped_column(
        Enum(FindingCategory, name="finding_category"), nullable=False
    )
    file_path: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    line_start: Mapped[int | None] = mapped_column(Integer, nullable=True)
    line_end: Mapped[int | None] = mapped_column(Integer, nullable=True)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    recommendation: Mapped[str | None] = mapped_column(Text, nullable=True)

    review: Mapped[Review] = relationship(back_populates="findings")


# ---------------------------------------------------------------------------
# Policy + PolicyResult
# ---------------------------------------------------------------------------


class Policy(Base):
    __tablename__ = "policies"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    enabled: Mapped[bool] = mapped_column(default=True, nullable=False)
    severity: Mapped[FindingSeverity] = mapped_column(
        Enum(FindingSeverity, name="finding_severity"),
        default=FindingSeverity.MEDIUM,
        nullable=False,
    )
    config_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )


class PolicyResult(Base):
    __tablename__ = "policy_results"
    __table_args__ = (Index("ix_policy_results_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    policy_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("policies.id"), nullable=False)
    status: Mapped[PolicyResultStatus] = mapped_column(
        Enum(PolicyResultStatus, name="policy_result_status"), nullable=False
    )
    message: Mapped[str | None] = mapped_column(Text, nullable=True)
    evidence_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="policy_results")


# ---------------------------------------------------------------------------
# Disagreement
# ---------------------------------------------------------------------------


class Disagreement(Base):
    __tablename__ = "disagreements"
    __table_args__ = (Index("ix_disagreements_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    topic: Mapped[str] = mapped_column(String(512), nullable=False)
    author_position: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewer_position: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    requires_human_decision: Mapped[bool] = mapped_column(default=True, nullable=False)
    resolution: Mapped[str | None] = mapped_column(Text, nullable=True)
    resolved_by_agent_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="disagreements")


# ---------------------------------------------------------------------------
# Approval
# ---------------------------------------------------------------------------


class Approval(Base):
    __tablename__ = "approvals"
    __table_args__ = (Index("ix_approvals_decision", "decision_id"),)

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    decision_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False
    )
    approver_agent_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("agents.id"), nullable=False)
    status: Mapped[ApprovalStatus] = mapped_column(
        Enum(ApprovalStatus, name="approval_status"), nullable=False
    )
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    decision: Mapped[Decision] = relationship(back_populates="approvals")


# ---------------------------------------------------------------------------
# Event — append-only audit log
# ---------------------------------------------------------------------------


class Event(Base):
    __tablename__ = "events"
    __table_args__ = (
        Index("ix_events_project_created", "project_id", "created_at"),
        Index("ix_events_entity", "entity_type", "entity_id"),
    )

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    project_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[UUID] = mapped_column(Uuid, nullable=False)
    event_type: Mapped[str] = mapped_column(String(128), nullable=False)
    actor_agent_id: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=True
    )
    payload_json: Mapped[dict[str, object] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, nullable=False
    )

    project: Mapped[Project] = relationship(back_populates="events")


__all__ = [
    "Agent",
    "Approval",
    "Base",
    "Decision",
    "Disagreement",
    "Event",
    "Finding",
    "GitChange",
    "Policy",
    "PolicyResult",
    "Project",
    "Review",
    "Task",
]
