"""baseline schema — captures the live 2026-05-11 state

Models covered: Project, Task, Decision, Approval, Disagreement, GitChange,
PolicyResult, Review, Finding, Event, User (incl. avatar_url), ApiToken,
Account, Session.

Existing deployments that already have these tables (created via
`Base.metadata.create_all` during Stage A/B) should be onboarded via
`alembic stamp head` — this baseline is then a no-op for them but
becomes the anchor for all subsequent migrations.

Fresh deploys run `alembic upgrade head` and get the full schema.

Revision ID: 21c163745df5
Revises:
Create Date: 2026-05-11 11:44:26.370922+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21c163745df5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('HUMAN', 'CLAUDE', 'CODEX', 'CURSOR', 'CLINE', 'AIDER', 'OTHER', name='agent_type'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finding_severity'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'GOOGLE', 'MAGIC_LINK', name='authprovider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('provider_login', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_accounts_provider_user_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_user_id', ['user_id'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.Enum('HUMAN', 'CLAUDE', 'CODEX', 'CURSOR', 'CLINE', 'AIDER', 'OTHER', name='agenttype', native_enum=False, length=32), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('hashed_secret', sa.String(length=64), nullable=False),
    sa.Column('scopes_csv', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_secret')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_api_tokens_prefix', ['prefix'], unique=False)
        batch_op.create_index('ix_api_tokens_user_id', ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor_agent_id', sa.Uuid(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_events_project_created', ['project_id', 'created_at'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'REVIEW_REQUIRED', 'APPROVED', 'REJECTED', 'CLOSED', name='task_status'), nullable=False),
    sa.Column('created_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'display_id', name='uq_tasks_project_display')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_project_status', ['project_id', 'status'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('author_agent_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW_REQUIRED', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED', name='decision_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'display_id', name='uq_decisions_project_display')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_project_status', ['project_id', 'status'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('approver_agent_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='approval_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('ix_approvals_decision', ['decision_id'], unique=False)

    op.create_table('disagreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('author_position', sa.Text(), nullable=True),
    sa.Column('reviewer_position', sa.Text(), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('requires_human_decision', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_agent_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disagreements', schema=None) as batch_op:
        batch_op.create_index('ix_disagreements_decision', ['decision_id'], unique=False)

    op.create_table('git_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('repo_path', sa.String(length=1024), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('diff_hash', sa.String(length=72), nullable=True),
    sa.Column('files_changed_json', sa.JSON(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('git_changes', schema=None) as batch_op:
        batch_op.create_index('ix_git_changes_commit', ['commit_hash'], unique=False)
        batch_op.create_index('ix_git_changes_decision', ['decision_id'], unique=False)

    op.create_table('policy_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'WARNING', 'BLOCKED', name='policy_result_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_results', schema=None) as batch_op:
        batch_op.create_index('ix_policy_results_decision', ['decision_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.String(length=32), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_agent_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'CHANGES_REQUESTED', 'COMMENTED', 'REJECTED', name='review_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_decision', ['decision_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finding_severity'), nullable=False),
    sa.Column('category', sa.Enum('SECURITY', 'PERFORMANCE', 'ARCHITECTURE', 'BUG', 'MAINTAINABILITY', 'TESTS', name='finding_category'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_decision')

    op.drop_table('reviews')
    with op.batch_alter_table('policy_results', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_results_decision')

    op.drop_table('policy_results')
    with op.batch_alter_table('git_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_git_changes_decision')
        batch_op.drop_index('ix_git_changes_commit')

    op.drop_table('git_changes')
    with op.batch_alter_table('disagreements', schema=None) as batch_op:
        batch_op.drop_index('ix_disagreements_decision')

    op.drop_table('disagreements')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_decision')

    op.drop_table('approvals')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decisions_project_status')

    op.drop_table('decisions')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_status')

    op.drop_table('tasks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')
        batch_op.drop_index('ix_sessions_expires_at')

    op.drop_table('sessions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_project_created')
        batch_op.drop_index('ix_events_entity')

    op.drop_table('events')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_api_tokens_user_id')
        batch_op.drop_index('ix_api_tokens_prefix')

    op.drop_table('api_tokens')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_user_id')

    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('policies')
    op.drop_table('agents')
    # ### end Alembic commands ###
