"""add device_codes table

Revision ID: aa2ce082f322
Revises: 21c163745df5
Create Date: 2026-05-11 12:01:14.396519+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa2ce082f322'
down_revision: Union[str, Sequence[str], None] = '21c163745df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_code', sa.String(length=16), nullable=False),
    sa.Column('requested_label', sa.String(length=255), nullable=False),
    sa.Column('requested_agent_type', sa.Enum('HUMAN', 'CLAUDE', 'CODEX', 'CURSOR', 'CLINE', 'AIDER', 'OTHER', name='agenttype', native_enum=False, length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code_hash'),
    sa.UniqueConstraint('user_code', name='uq_device_codes_user_code')
    )
    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.create_index('ix_device_codes_device_code_hash', ['device_code_hash'], unique=False)
        batch_op.create_index('ix_device_codes_expires_at', ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_device_codes_expires_at')
        batch_op.drop_index('ix_device_codes_device_code_hash')

    op.drop_table('device_codes')
    # ### end Alembic commands ###
